# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

format = """\
$directory\
$git_branch\
$fill\
${custom.kubectx}(:${custom.kubens})\
$aws
$character\
"""
continuation_prompt = 'â–¶ '

[fill]
symbol = " "

[git_branch]
format = 'on [$symbol$branch]($style)'
style = 'bold red'

[git_status]
disabled = true

[custom.kubectx]
style = 'bold blue'
command = "echo \ue81d ${$(kubectl config current-context 2>/dev/null)##*/} "
format = '[$output]($style)'
when = true

[custom.kubens]
style = 'bold red'
command = 'kubectl config view --minify -o "jsonpath={..namespace} 2>/dev/null"'
format = '[$output]($style)'
when = true


[aws]
format = ' on [$profile](bold fg:yellow)(:[$region](fg:yellow))'
force_display = true
